default_route:
    path: /
    defaults:
        _controller: App\Controller\DefaultController::index
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api_login_check:
    path: /api/login_check
